### PR TITLE
optional codegen fix

### PR DESCRIPTION
**Pull request by lg08**
Hey @lpil !

Thanks so much for this repo!
I was throwing together a little build tool for this package and noticed a little bug in the codegen for optional properties.

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Ah! Thank you very much!

**Comment by lpil** [comment]
Ah! Looks like there's an extra newline in the snapshots. Could you re-run `birdie` to fix them please 🙏 

If you could update the changelog too that would be fab

**Comment by lg08** [comment]
Whoops, sorry about that! Just updated and tests seem to be passing now.
Took a shot at updating the changelog - lemme know if I should adjust it at all!

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
